```{r reg, cache=cacheon, fig.cap=paste0("Registration over time, ", global_year - 5, "-", global_year), fig.width=9.5, fig.height=7}

tot <- rsdata %>%
  filter(indexyear %in% paste(seq((global_year - 5), global_year, 1))) %>%
  count(indexyear) %>%
  mutate(
    byvar = 5,
    byvarname = "Total index och follow-up"
  )

totun <- rsdata %>%
  filter(indexyear %in% paste(seq((global_year - 5), global_year, 1))) %>%
  group_by(patientreference, indexyear) %>%
  slice(1) %>%
  ungroup() %>%
  count(indexyear) %>%
  mutate(
    byvar = 6,
    byvarname = "Unique patients"
  )

type <- rsdata %>%
  filter(indexyear %in% paste(seq((global_year - 5), global_year, 1))) %>%
  group_by(indexyear) %>%
  count(ttype) %>%
  mutate(
    byvar = 1:n(),
    byvarname = ttype
  ) %>%
  ungroup() %>%
  select(-ttype)

hfdur <- rsdata %>%
  filter(indexyear %in% paste(seq((global_year - 5), global_year, 1)), ttype == "Index") %>%
  filter(!is.na(hfdur)) %>%
  group_by(indexyear) %>%
  count(hfdur) %>%
  mutate(
    byvar = 1 + (1:n()) / 100,
    byvarname = hfdur
  ) %>%
  ungroup() %>%
  select(-hfdur)

all <- bind_rows(tot, totun, type, hfdur) %>%
  pivot_wider(names_from = indexyear, values_from = n) %>%
  arrange(byvar) %>%
  select(-byvar)

plotall <- all %>%
  mutate(across(where(is.integer), ~.x)) %>%
  select(-byvarname) %>%
  t()

cexmy <- 1
# c(bottom, left, top, right) default c(5, 4, 4, 2) + 0.1.
par(mar = c(4, 5, 0.5, 0.5) + 0.1)

plot(1,
  type = "n",
  ylim = c(0, 20000),
  xlim = c(1 - 0.1, length((global_year - 5):global_year) + 0.1),
  axes = F,
  xaxs = "i",
  yaxs = "i",
  ylab = "",
  xlab = labnams[1],
  cex.lab = cexmy
)

xa <- c((global_year - 5):global_year)
ya <- c(seq(0, 20000, 2000))

abline(v = 1:length(xa), lty = 1, col = "gray", lwd = 1)
abline(h = ya, lty = 1, col = "gray", lwd = 1)

matplot(plotall,
  type = "b",
  # type = "l",
  pch = 19,
  col = global_cols[c(1, 2, 3, 4, 5, 6, 7, 8)],
  lty = 1,
  lwd = 3,
  # cex = 1.2,
  # axes = FALSE,
  # xaxs = "i",
  # yaxs = "i",
  # xlim = c(1 - 0.2, length((global_year - 5):global_year) + 0.2),
  # ylab = "",
  # xlab = labnams[1],
  cex.lab = cexmy,
  # ylim = c(0, 20000),
  add = T
)

box(bty = "l")

axis(2,
  at = ya,
  fnbm(ya),
  cex.axis = cexmy, las = 2
)

axis(2, at = 10000, "Number of registrations", cex.axis = cexmy, tick = FALSE, line = 3)

axis(1, at = 1:length(xa), labels = xa, cex.axis = cexmy)

legend(
  x = 0.85, y = 20300, all %>% pull(byvarname),
  col = global_cols[c(1, 2, 3, 4, 5, 6, 7, 8)],
  lwd = 3, bty = "n", cex = cexmy
)
```

```{r, cache=cacheon}

all <- all %>%
  mutate(byvarname = str_replace_all(byvarname, fixed("\u2265"), "$\\geq$")) %>%
  mutate(across(where(is.numeric), fnbm))

colnams <- colnames(all)
colnams[1] <- ""
colnames(all) <- colnams

write.xlsx(all, paste0("./output/tabs/registrering_", Sys.Date(), ".xlsx"), rowNames = FALSE, overwrite = T)

default_kable(all, caption = paste0("Registration over time, ", global_year - 5, "-", global_year), escape = F, align = c("l", rep("c", ncol(all) - 1)))
```
