```{r, cache=cacheon}
tabvars <- c(
  "vtype", "sex", "age", "hfdurindex", "ef_cat3", "FUNCTION_CLASS_NYHA", "LIFEQUALITY_SCORE",
  "EARLIER_CARDIAC_ARREST", "REVASCULARIZATION", "HYPERTENSION",
  "ATRIAL_FIBRILLATION_FLUTTER", "DIABETES",
  "CHRONIC_LUNG_DISEASE", "HEART_VALVE_DISEASE",
  "HEART_VALVE_SURGERY", "DILATED_CARDIOMYOPATHY",
  "PRIMARY_ETIOLOGY",
  "BP_SYSTOLIC", "BP_DIASTOLIC", "HEART_FREQUENCY",
  "B_HB", "S_CREATININE",
  "S_POTASSIUM", "S_SODIUM",
  "NT_PROBNP", "S_FERRITIN", "P_TRANSFERRIN"
)

tmprsdata <- rsdata %>%
  filter(indexyear == global_year)
```

```{r, cache=cacheon}

tab1 <- table1(
  data = tmprsdata,
  stratvar = "ttype",
  vars = tabvars
)

tab1 <- tab1 %>%
  mutate(
    var = case_when(
      var == "n" ~ "Sweden",
      var == "vtype" ~ "Unit type, n (%)",
      var == "sex" ~ "Sex, n (%)",
      var == "age" ~ "Age (year), median [Q1-Q3]",
      var == "hfdurindex" ~ "HF duration at index (mo), n (%)",
      var == "ef_cat3" ~ "LVEF (%), n (%)",
      var == "FUNCTION_CLASS_NYHA" ~ "NYHA class, n (%)",
      var == "LIFEQUALITY_SCORE" ~ "QoL EQ-5D, median [Q1-Q3]",
      var == "PRIMARY_ETIOLOGY" ~ "Primary etiology, n (%)",
      var == "DIABETES" ~ "Diabetes, n (%)",
      var == "EARLIER_CARDIAC_ARREST" ~ "Previous heart attack, n (%)",
      var == "ATRIAL_FIBRILLATION_FLUTTER" ~ "Atrial fibrillation/flutter, n (%)",
      var == "HYPERTENSION" ~ "Hypertension, n (%)",
      var == "DILATED_CARDIOMYOPATHY" ~ "Dilated cardiomyopathy, n (%)",
      var == "HEART_VALVE_DISEASE" ~ "Heart valve disease, n (%)",
      var == "REVASCULARIZATION" ~ "Revascularization, n (%)",
      var == "CHRONIC_LUNG_DISEASE" ~ "Chronic lung disease, n (%)",
      var == "HEART_VALVE_SURGERY" ~ "Valve surgery, n (%)",
      var == "BP_SYSTOLIC" ~ "Systolic blood pressure (mmHg), median [Q1-Q3]",
      var == "BP_DIASTOLIC" ~ "Diastolic blood pressure (mmHg), median [Q1-Q3]",
      var == "HEART_FREQUENCY" ~ "Heart rate (slag/min), median [Q1-Q3]",
      var == "NT_PROBNP" ~ "NT-proBNP (pg/m/L), median [Q1-Q3]",
      var == "S_CREATININE" ~ "Creatinine (umol/L), median [Q1-Q3]",
      var == "S_POTASSIUM" ~ "Potassium (mmol/L), median [Q1-Q3]",
      var == "S_SODIUM" ~ "Sodium (mmol/L), median [Q1-Q3]",
      var == "B_HB" ~ "Hemoglobin (g/L), median [Q1-Q3]",
      var == "P_TRANSFERRIN" ~ "Transferrin (%), median [Q1-Q3]",
      var == "S_FERRITIN" ~ "Ferritin (ug/l), median [Q1-Q3]"
    ),
    level = str_replace_all(level, fixed("HF duration "), ""),
    level = str_replace_all(level, fixed(" mo at index"), ""),
    level = str_replace_all(level, fixed("\u2265"), "$\\geq$")
  ) %>%
  mutate(across(everything(), ~ str_replace_all(.x, fixed("0 (NaN)"), ""))) %>%
  mutate(across(everything(), ~ str_replace_all(.x, fixed("(%)"), "(\\%)")))

## fix in order to use escape = TRUE
colnames(tab1) <- c(colnames(tab1) <- c("", "", levels(rsdata$ttype)))

default_kable(tab1,
  font_size = 6,
  caption = paste0("Characteristics for patients registred during ", global_year),
  escape = FALSE,
  align = c("l", "l", rep("c", ncol(tab1) - 2))
)
```

\blandscape

```{r, cache=cacheon, dependson="tabs"}

tab1 <- table1(
  data = tmprsdata %>% filter(!is.na(sex)),
  stratvar = c("sex", "ttype"),
  vars = tabvars[tabvars != "sex"]
)

tab1 <- tab1 %>%
  mutate(
    var = case_when(
      var == "n" ~ "Sweden",
      var == "vtype" ~ "Unit type, n (%)",
      var == "sex" ~ "Sex, n (%)",
      var == "age" ~ "Age (year), median [Q1-Q3]",
      var == "hfdurindex" ~ "HF duration at index (mo), n (%)",
      var == "ef_cat3" ~ "LVEF (%), n (%)",
      var == "FUNCTION_CLASS_NYHA" ~ "NYHA class, n (%)",
      var == "LIFEQUALITY_SCORE" ~ "QoL EQ-5D, median [Q1-Q3]",
      var == "PRIMARY_ETIOLOGY" ~ "Primary etiology, n (%)",
      var == "DIABETES" ~ "Diabetes, n (%)",
      var == "EARLIER_CARDIAC_ARREST" ~ "Previous heart attack, n (%)",
      var == "ATRIAL_FIBRILLATION_FLUTTER" ~ "Atrial fibrillation/flutter, n (%)",
      var == "HYPERTENSION" ~ "Hypertension, n (%)",
      var == "DILATED_CARDIOMYOPATHY" ~ "Dilated cardiomyopathy, n (%)",
      var == "HEART_VALVE_DISEASE" ~ "Heart valve disease, n (%)",
      var == "REVASCULARIZATION" ~ "Revascularization, n (%)",
      var == "CHRONIC_LUNG_DISEASE" ~ "Chronic lung disease, n (%)",
      var == "HEART_VALVE_SURGERY" ~ "Valve surgery, n (%)",
      var == "BP_SYSTOLIC" ~ "Systolic blood pressure (mmHg), median [Q1-Q3]",
      var == "BP_DIASTOLIC" ~ "Diastolic blood pressure (mmHg), median [Q1-Q3]",
      var == "HEART_FREQUENCY" ~ "Heart rate (slag/min), median [Q1-Q3]",
      var == "NT_PROBNP" ~ "NT-proBNP (pg/m/L), median [Q1-Q3]",
      var == "S_CREATININE" ~ "Creatinine (umol/L), median [Q1-Q3]",
      var == "S_POTASSIUM" ~ "Potassium (mmol/L), median [Q1-Q3]",
      var == "S_SODIUM" ~ "Sodium (mmol/L), median [Q1-Q3]",
      var == "B_HB" ~ "Hemoglobin (g/L), median [Q1-Q3]",
      var == "P_TRANSFERRIN" ~ "Transferrin (%), median [Q1-Q3]",
      var == "S_FERRITIN" ~ "Ferritin (ug/l), median [Q1-Q3]"
    ),
    level = str_replace_all(level, fixed("HF duration "), ""),
    level = str_replace_all(level, fixed(" mo at index"), ""),
    level = str_replace_all(level, fixed("\u2265"), "$\\geq$")
  ) %>%
  mutate(across(everything(), ~ str_replace_all(.x, fixed("0 (NaN)"), ""))) %>%
  mutate(across(everything(), ~ str_replace_all(.x, fixed("(%)"), "(\\%)")))

## fix in order to use escape = TRUE
colnames(tab1) <- c("", "", rep(levels(rsdata$sex), 4))

myHeader <- c(" " = 2, " " = 2, " " = 2, " " = 2, " " = 2)
names(myHeader) <- c(
  " ", shortttype[1],
  paste0(shortttype[2], " follow-up"),
  paste0(shortttype[3], " follow-up"),
  paste0(shortttype[4], " follow-up")
)

default_kable(tab1,
  font_size = 6,
  #caption = paste0("Characteristics for patients registred during ", global_year, " by sex"),
  escape = FALSE,
  align = c("l", "l", rep("c", ncol(tab1) - 2))
) %>% add_header_above(myHeader)
```

\elandscape
